Add missing include for struct timeval
Fix build failure with musl libc:
socketcanbackend.h:88:38: error: 'timeval' was not declared in this scope

Change-Id: I4089f5a906095c21b2790d35ad131d9a0713ff3b